# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24f283d94aa672753b45dc0adc9b8fd34f65b170831fa25d4bd947d000b685eb98e3c9f8f8d4d55caea60c1276899c85ab2558f9a5399b1d8145fe7741f3616e

test:
  secret_key_base: a574174a3bcf6d470440fd9c53de3dd9f9cdf0842b7d4207bad8d389ed66e230ad6175fde5e3a9ca654fa11afb9f0ced2eec753da46e64fbc0ee90746478ca80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
